-- MySQL Script generated by MySQL Workbench
-- Wed Sep  7 20:23:27 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema oscarbooks
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `oscarbooks` ;

-- -----------------------------------------------------
-- Schema oscarbooks
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `oscarbooks` DEFAULT CHARACTER SET utf8 ;
USE `oscarbooks` ;

-- -----------------------------------------------------
-- Table `oscarbooks`.`customeraddress`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oscarbooks`.`customeraddress` ;

CREATE TABLE IF NOT EXISTS `oscarbooks`.`customeraddress` (
  `custaddressid` INT(5) NOT NULL AUTO_INCREMENT,
  `customerid` INT(5) NOT NULL,
  `custstreet` VARCHAR(30) NULL,
  `custcity` VARCHAR(30) NULL,
  `custstate` VARCHAR(30) NULL,
  `custzip` VARCHAR(20) NULL,
  `custcountry` VARCHAR(30) NULL,
  PRIMARY KEY (`custaddressid`),
  INDEX `addresstocustomer_idx` (`customerid` ASC) VISIBLE,
  UNIQUE INDEX `custaddressid_UNIQUE` (`custaddressid` ASC) VISIBLE,
  CONSTRAINT `addresstocustomer`
    FOREIGN KEY (`customerid`)
    REFERENCES `oscarbooks`.`customers` (`customerid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oscarbooks`.`customeremail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oscarbooks`.`customeremail` ;

CREATE TABLE IF NOT EXISTS `oscarbooks`.`customeremail` (
  `custemailid` INT(5) NOT NULL AUTO_INCREMENT,
  `customerid` INT(5) NOT NULL,
  `custemailaddress` VARCHAR(60) NULL,
  PRIMARY KEY (`custemailid`),
  INDEX `emailtocustomer_idx` (`customerid` ASC) VISIBLE,
  UNIQUE INDEX `custemailid_UNIQUE` (`custemailid` ASC) VISIBLE,
  CONSTRAINT `emailtocustomer`
    FOREIGN KEY (`customerid`)
    REFERENCES `oscarbooks`.`customers` (`customerid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oscarbooks`.`customerphone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oscarbooks`.`customerphone` ;

CREATE TABLE IF NOT EXISTS `oscarbooks`.`customerphone` (
  `custphoneid` INT(5) NOT NULL AUTO_INCREMENT,
  `customerid` INT(5) NOT NULL,
  `custphonenumber` VARCHAR(20) NULL,
  PRIMARY KEY (`custphoneid`),
  INDEX `phonetocustomer_idx` (`customerid` ASC) VISIBLE,
  UNIQUE INDEX `custphoneid_UNIQUE` (`custphoneid` ASC) VISIBLE,
  CONSTRAINT `phonetocustomer`
    FOREIGN KEY (`customerid`)
    REFERENCES `oscarbooks`.`customers` (`customerid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oscarbooks`.`customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oscarbooks`.`customers` ;

CREATE TABLE IF NOT EXISTS `oscarbooks`.`customers` (
  `customerid` INT(5) NOT NULL AUTO_INCREMENT,
  `custfname` VARCHAR(20) NULL,
  `custmname` VARCHAR(20) NULL,
  `custlname` VARCHAR(20) NULL,
  PRIMARY KEY (`customerid`),
  UNIQUE INDEX `customerid_UNIQUE` (`customerid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oscarbooks`.`employeeaddress`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oscarbooks`.`employeeaddress` ;

CREATE TABLE IF NOT EXISTS `oscarbooks`.`employeeaddress` (
  `empaddressid` INT(5) NOT NULL AUTO_INCREMENT,
  `employeeid` INT(5) NOT NULL,
  `empstreet` VARCHAR(30) NULL,
  `empcity` VARCHAR(30) NULL,
  `empstate` VARCHAR(30) NULL,
  `empzip` VARCHAR(20) NULL,
  `empcountry` VARCHAR(30) NULL,
  PRIMARY KEY (`empaddressid`),
  INDEX `addresstoemployee_idx` (`employeeid` ASC) VISIBLE,
  UNIQUE INDEX `empaddressid_UNIQUE` (`empaddressid` ASC) VISIBLE,
  CONSTRAINT `addresstoemployee`
    FOREIGN KEY (`employeeid`)
    REFERENCES `oscarbooks`.`employees` (`employeeid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oscarbooks`.`employeeemail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oscarbooks`.`employeeemail` ;

CREATE TABLE IF NOT EXISTS `oscarbooks`.`employeeemail` (
  `employeeemailid` INT(5) NOT NULL AUTO_INCREMENT,
  `employeeid` INT(5) NOT NULL,
  `empemailaddress` VARCHAR(60) NULL,
  PRIMARY KEY (`employeeemailid`),
  INDEX `emailtoemployee_idx` (`employeeid` ASC) VISIBLE,
  UNIQUE INDEX `employeeemailid_UNIQUE` (`employeeemailid` ASC) VISIBLE,
  CONSTRAINT `emailtoemployee`
    FOREIGN KEY (`employeeid`)
    REFERENCES `oscarbooks`.`employees` (`employeeid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oscarbooks`.`employeephone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oscarbooks`.`employeephone` ;

CREATE TABLE IF NOT EXISTS `oscarbooks`.`employeephone` (
  `employeephoneid` INT(5) NOT NULL AUTO_INCREMENT,
  `employeeid` INT(5) NOT NULL,
  `empnumber` VARCHAR(20) NULL,
  PRIMARY KEY (`employeephoneid`),
  INDEX `phonetoemail_idx` (`employeeid` ASC) VISIBLE,
  UNIQUE INDEX `employeephoneid_UNIQUE` (`employeephoneid` ASC) VISIBLE,
  CONSTRAINT `phonetoemail`
    FOREIGN KEY (`employeeid`)
    REFERENCES `oscarbooks`.`employees` (`employeeid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oscarbooks`.`employees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oscarbooks`.`employees` ;

CREATE TABLE IF NOT EXISTS `oscarbooks`.`employees` (
  `employeeid` INT(5) NOT NULL AUTO_INCREMENT,
  `empidnumber` INT(5) NOT NULL,
  `empfname` VARCHAR(20) NOT NULL,
  `empmname` VARCHAR(20) NULL,
  `emplname` VARCHAR(20) NOT NULL,
  `empposition` VARCHAR(20) NOT NULL,
  `emphiredate` DATE NOT NULL,
  `emptime` SET('full', 'part', 'casual') NOT NULL,
  `empmanagement` TINYINT(1) NOT NULL,
  PRIMARY KEY (`employeeid`),
  UNIQUE INDEX `employeeid_UNIQUE` (`employeeid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oscarbooks`.`inventory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oscarbooks`.`inventory` ;

CREATE TABLE IF NOT EXISTS `oscarbooks`.`inventory` (
  `inventoryid` INT(5) NOT NULL AUTO_INCREMENT,
  `productid` INT(5) NOT NULL,
  `prdinventory` INT(5) NOT NULL DEFAULT 0,
  `prdsetprice` DECIMAL(10,2) NULL,
  PRIMARY KEY (`inventoryid`),
  INDEX `inventorytoproduct_idx` (`productid` ASC) VISIBLE,
  UNIQUE INDEX `inventoryid_UNIQUE` (`inventoryid` ASC) VISIBLE,
  CONSTRAINT `inventorytoproduct`
    FOREIGN KEY (`productid`)
    REFERENCES `oscarbooks`.`products` (`productid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oscarbooks`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oscarbooks`.`products` ;

CREATE TABLE IF NOT EXISTS `oscarbooks`.`products` (
  `productid` INT(5) NOT NULL AUTO_INCREMENT,
  `prdname` VARCHAR(45) NOT NULL,
  `prddescription` VARCHAR(200) NULL,
  PRIMARY KEY (`productid`),
  UNIQUE INDEX `productid_UNIQUE` (`productid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oscarbooks`.`purchasetransactionitem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oscarbooks`.`purchasetransactionitem` ;

CREATE TABLE IF NOT EXISTS `oscarbooks`.`purchasetransactionitem` (
  `ptxnitemid` INT(5) NOT NULL AUTO_INCREMENT,
  `ptxnid` INT(5) NOT NULL,
  `productid` INT(5) NOT NULL,
  `ptxnunitprice` DECIMAL(10,2) NOT NULL,
  `ptxnquantity` INT(5) NOT NULL,
  `ptxndiscount` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  PRIMARY KEY (`ptxnitemid`),
  INDEX `ptxntoproduct_idx` (`productid` ASC) VISIBLE,
  INDEX `ptxndetailtoptxn_idx` (`ptxnid` ASC) VISIBLE,
  UNIQUE INDEX `ptxnitemid_UNIQUE` (`ptxnitemid` ASC) VISIBLE,
  CONSTRAINT `ptxnitemtoproduct`
    FOREIGN KEY (`productid`)
    REFERENCES `oscarbooks`.`products` (`productid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ptxnitemtoptxn`
    FOREIGN KEY (`ptxnid`)
    REFERENCES `oscarbooks`.`purchasetransactions` (`ptxnid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oscarbooks`.`purchasetransactions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oscarbooks`.`purchasetransactions` ;

CREATE TABLE IF NOT EXISTS `oscarbooks`.`purchasetransactions` (
  `ptxnid` INT(5) NOT NULL AUTO_INCREMENT,
  `vendorid` INT(5) NULL,
  `invoicenumber` INT(5) NULL,
  `employeeid` INT(5) NULL,
  `ptxndate` DATE NOT NULL,
  `ptxntotal` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`ptxnid`),
  INDEX `ptxntovendor_idx` (`vendorid` ASC) VISIBLE,
  INDEX `ptxntoemployees_idx` (`employeeid` ASC) VISIBLE,
  UNIQUE INDEX `ptxnid_UNIQUE` (`ptxnid` ASC) VISIBLE,
  UNIQUE INDEX `invoicenumber_UNIQUE` (`invoicenumber` ASC) VISIBLE,
  CONSTRAINT `ptxntovendor`
    FOREIGN KEY (`vendorid`)
    REFERENCES `oscarbooks`.`vendors` (`vendorid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ptxntoemployees`
    FOREIGN KEY (`employeeid`)
    REFERENCES `oscarbooks`.`employees` (`employeeid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oscarbooks`.`salestransactionitem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oscarbooks`.`salestransactionitem` ;

CREATE TABLE IF NOT EXISTS `oscarbooks`.`salestransactionitem` (
  `stxnitemid` INT(5) NOT NULL AUTO_INCREMENT,
  `stxnid` INT(5) NOT NULL,
  `productid` INT(5) NOT NULL,
  `stxnunitprice` DECIMAL(10,2) NOT NULL,
  `stxnquantity` INT(5) NOT NULL,
  `stxndiscount` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  PRIMARY KEY (`stxnitemid`),
  INDEX `stxnid_idx` (`stxnid` ASC) VISIBLE,
  INDEX `detailstoproduct_idx` (`productid` ASC) VISIBLE,
  UNIQUE INDEX `stxnitemid_UNIQUE` (`stxnitemid` ASC) VISIBLE,
  CONSTRAINT `stxnitemtosalestrxn`
    FOREIGN KEY (`stxnid`)
    REFERENCES `oscarbooks`.`salestransactions` (`stxnid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `stxnitemtoproduct`
    FOREIGN KEY (`productid`)
    REFERENCES `oscarbooks`.`products` (`productid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oscarbooks`.`salestransactions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oscarbooks`.`salestransactions` ;

CREATE TABLE IF NOT EXISTS `oscarbooks`.`salestransactions` (
  `stxnid` INT(5) NOT NULL AUTO_INCREMENT,
  `customerid` INT(5) NOT NULL,
  `employeeid` INT(5) NOT NULL,
  `stxndate` DATE NOT NULL,
  `stxnamount` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`stxnid`),
  INDEX `trxntocustomer_idx` (`customerid` ASC) VISIBLE,
  INDEX `strxntoemployees_idx` (`employeeid` ASC) VISIBLE,
  UNIQUE INDEX `stxnid_UNIQUE` (`stxnid` ASC) VISIBLE,
  CONSTRAINT `strxntocustomer`
    FOREIGN KEY (`customerid`)
    REFERENCES `oscarbooks`.`customers` (`customerid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `strxntoemployees`
    FOREIGN KEY (`employeeid`)
    REFERENCES `oscarbooks`.`employees` (`employeeid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oscarbooks`.`vendoraddress`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oscarbooks`.`vendoraddress` ;

CREATE TABLE IF NOT EXISTS `oscarbooks`.`vendoraddress` (
  `vendoraddressid` INT(5) NOT NULL AUTO_INCREMENT,
  `vendorid` INT(5) NOT NULL,
  `venstreet` VARCHAR(30) NULL,
  `vencity` VARCHAR(30) NULL,
  `venstate` VARCHAR(30) NULL,
  `venzip` VARCHAR(20) NULL,
  `vencountry` VARCHAR(30) NULL,
  PRIMARY KEY (`vendoraddressid`),
  INDEX `addresstovendor_idx` (`vendorid` ASC) VISIBLE,
  UNIQUE INDEX `vendoraddressid_UNIQUE` (`vendoraddressid` ASC) VISIBLE,
  CONSTRAINT `addresstovendor`
    FOREIGN KEY (`vendorid`)
    REFERENCES `oscarbooks`.`vendors` (`vendorid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oscarbooks`.`vendoremail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oscarbooks`.`vendoremail` ;

CREATE TABLE IF NOT EXISTS `oscarbooks`.`vendoremail` (
  `vendoremailid` INT(5) NOT NULL AUTO_INCREMENT,
  `vendorid` INT(5) NOT NULL,
  `venemailaddress` VARCHAR(60) NULL,
  PRIMARY KEY (`vendoremailid`),
  INDEX `emailtovendor_idx` (`vendorid` ASC) VISIBLE,
  UNIQUE INDEX `vendoremailid_UNIQUE` (`vendoremailid` ASC) VISIBLE,
  CONSTRAINT `emailtovendor`
    FOREIGN KEY (`vendorid`)
    REFERENCES `oscarbooks`.`vendors` (`vendorid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oscarbooks`.`vendorphone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oscarbooks`.`vendorphone` ;

CREATE TABLE IF NOT EXISTS `oscarbooks`.`vendorphone` (
  `vendorphoneid` INT(5) NOT NULL AUTO_INCREMENT,
  `vendorid` INT(5) NOT NULL,
  `vennumber` VARCHAR(20) NULL,
  PRIMARY KEY (`vendorphoneid`),
  INDEX `phonetovendors_idx` (`vendorid` ASC) VISIBLE,
  UNIQUE INDEX `vendorphoneid_UNIQUE` (`vendorphoneid` ASC) VISIBLE,
  CONSTRAINT `phonetovendors`
    FOREIGN KEY (`vendorid`)
    REFERENCES `oscarbooks`.`vendors` (`vendorid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oscarbooks`.`vendors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oscarbooks`.`vendors` ;

CREATE TABLE IF NOT EXISTS `oscarbooks`.`vendors` (
  `vendorid` INT(5) NOT NULL AUTO_INCREMENT,
  `venrefnbr` INT(5) NOT NULL,
  `venname` VARCHAR(45) NOT NULL,
  `venrep` VARCHAR(45) NULL,
  `last` DATE NULL,
  `first` DATE NULL,
  PRIMARY KEY (`vendorid`),
  UNIQUE INDEX `vendorid_UNIQUE` (`vendorid` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
