# Generated by Django 4.1 on 2022-08-24 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('albumid', models.AutoField(db_column='albumID', primary_key=True, serialize=False)),
                ('albumtitle', models.CharField(db_column='albumTitle', max_length=100)),
                ('albumyear', models.IntegerField(db_column='albumYear')),
                ('albumformat', models.CharField(blank=True, db_column='albumFormat', max_length=5, null=True)),
                ('songcount', models.IntegerField(db_column='songCount')),
                ('genre', models.CharField(blank=True, max_length=73, null=True)),
                ('recordinglocation', models.CharField(blank=True, db_column='recordingLocation', max_length=2, null=True)),
                ('releasedate', models.DateField(blank=True, db_column='releaseDate', null=True)),
                ('goingprice', models.DecimalField(blank=True, db_column='goingPrice', decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'db_table': 'albums',
            },
        ),
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('artistid', models.AutoField(db_column='artistID', primary_key=True, serialize=False)),
                ('artistname', models.CharField(db_column='artistName', max_length=40)),
                ('artistnationality', models.CharField(db_column='artistNationality', max_length=20)),
                ('artistbirthyear', models.IntegerField(db_column='artistBirthYear')),
                ('artistdeathyear', models.IntegerField(blank=True, db_column='artistDeathYear', null=True)),
            ],
            options={
                'db_table': 'artists',
            },
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('songid', models.AutoField(db_column='songID', primary_key=True, serialize=False)),
                ('songtitle', models.CharField(db_column='songTitle', max_length=100)),
                ('genre', models.CharField(max_length=20)),
                ('scorefromseven', models.IntegerField(db_column='scoreFromSeven')),
                ('albumid', models.ForeignKey(blank=True, db_column='albumID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.albums')),
            ],
            options={
                'db_table': 'songs',
            },
        ),
        migrations.AddField(
            model_name='albums',
            name='artistid',
            field=models.ForeignKey(blank=True, db_column='artistID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.artists'),
        ),
    ]
