# Generated by Django 4.1 on 2022-08-24 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='songs',
            table=None,
        ),
    ]
